/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "LSTD_TYPES.h"
#include "LBIT_MATH.h"
#include "MNVIC_Interface.h"
#include "MSTK_Interface.h"
#include "MRCC_Interface.h"
#include "MGPIO_Interface.h"
#include "MUSART_Interface.h"
#include "MADC_Interface.h"
#include "MDMA_Interface.h"
#include "MGPT_Interface.h"
#include "main.h"

u16 APP_u16IRData[2];
/* NOTE THAT:
 * THE RECEIVED STRING FROM THE BLUETOOTH MUST BE EXACTLY EQUAL TO THIS LENGTH
 * OR THIS LENGTH - 2, AS THERE ARE 2 DATA BYTES "\r\n" TRANSMITTED AUTOMATICALLY BY THE BLUETOOTH
 */
u8 APP_u8String[APP_MOBILE_MESSAGE_LENGTH];

void APP_vInit(void) {
	/********************* CLOCK CONFIGURATIONS AND BUSSES/PERIPHERALS ENABLE *********************/
	/* INIT CLOCK AND BUSSES CLOCK */
	MRCC_vInitSysAndBusClock();
	/* INIT ALL NEEDED PERIPHERALS CLOCK */
	MRCC_vEnablePeriphClock(MRCC_BUS_AHB1, MRCC_AHB1_GPIOAEN);
	MRCC_vEnablePeriphClock(MRCC_BUS_AHB1, MRCC_AHB1_GPIOBEN);
	MRCC_vEnablePeriphClock(MRCC_BUS_APB2, MRCC_APB2_ADC1EN);
	MRCC_vEnablePeriphClock(MRCC_BUS_AHB1, MRCC_AHB1_DMA2EN);
	MRCC_vEnablePeriphClock(MRCC_BUS_APB2, MRCC_APB2_USART1EN);
	MRCC_vEnablePeriphClock(MRCC_BUS_APB1, MRCC_APB1_TIM3EN);
	/**********************************************************************************************/

	/************************************* PINS CONFIGURATION *************************************/
	/* INIT ANALOG READ PINS */
	MGPIO_vSetPinMode(APP_IR0, MGPIO_MODE_ANALOG);
	MGPIO_vSetPinMode(APP_IR1, MGPIO_MODE_ANALOG);
	/* INIT USART TRANSMIT RECEIVE PINS */
	MGPIO_vSetPinMode(APP_MOBILE_USART_TX, MGPIO_MODE_ALTERNATE);
	MGPIO_vSetPinMode(APP_MOBILE_USART_RX, MGPIO_MODE_ALTERNATE);
	MGPIO_vSetPinAFDirection(APP_MOBILE_USART_TX, APP_MOBILE_USART_AF);
	MGPIO_vSetPinAFDirection(APP_MOBILE_USART_RX, APP_MOBILE_USART_AF);
	/* INIT TIMER PWM PIN */
	MGPIO_vSetPinMode(GPIOB, MGPIO_PIN04, MGPIO_MODE_ALTERNATE);
	MGPIO_vSetPinAFDirection(GPIOB, MGPIO_PIN04, MGPIO_AF02);
	/**********************************************************************************************/

	/************************************* ADC CONFIGURATIONS *************************************/
	/* INITIALIZE ADC */
	MADC_vInit();
	/* SET THE NUMBER OF CONVERSIONS TO THE NUMBER OF IRS IN THE ARRAY */
	MADC_vSetNumberOfConversions(MADC_REGULAR_GROUP, MADC_TWO_CONVERSIONS);
	/* SET ALL OF THEIR SAMPLE TIMES */
	MADC_vSetSamplingTime(APP_IR0_CHANNEL, MADC_SAMPLING_CYCLES_3);
	MADC_vSetSamplingTime(APP_IR1_CHANNEL, MADC_SAMPLING_CYCLES_3);
	/* SET THEIR SEQUENCE */
	MADC_vSetSequence(MADC_REGULAR_GROUP, APP_IR0_CHANNEL, MADC_SEQUENCE_1);
	MADC_vSetSequence(MADC_REGULAR_GROUP, APP_IR1_CHANNEL, MADC_SEQUENCE_2);
	/**********************************************************************************************/

	/********************************* DMA CONFIGURATIONS FOR ADC *********************************/
	volatile u32* DMAsrcAddr = MADC_u32SetRegularDMA(MADC_ENABLE);
	/* Enable DMA */
	MDMA_DirectInitType dma = {MDMA_DISABLE, MDMA_DIRECTION_PER_MEM, MDMA_ENABLE,
								MDMA_DISABLE, MDMA_ENABLE, MDMA_PRIORITY_VHIGH, MDMA_CHANNEL_0};
	MDMA_TransferStruct dmat = {(u32*)DMAsrcAddr, (u32*)APP_u16IRData, 2, MDMA_SIZE_HWORD};
	MDMA_vDirectInit(DMA2, MDMA_STREAM_0, &dma);
	MDMA_vStart(DMA2, MDMA_STREAM_0, &dmat);
	MADC_vEnable(MADC_ENABLE, MADC_DISABLE);
	/**********************************************************************************************/

	/************************************ USART CONFIGURATIONS ************************************/
	/* Initialize USART */
	MUSART_InitTypeDef uart = {9600, MUSART_DATAWIDTH_8BIT,
							MUSART_STOP_ONE_BIT, MUSART_DISABLE,
							MUSART_PARITY_EVEN, MUSART_DIRECTION_TX_RX,
							MUSART_DISABLE, MUSART_OVER_SAMPLING_16};
	MUSART_ClockInitTypeDef uart_clock = {MUSART_DISABLE,0,0,0};		/* Disable USART's Clock */
	MUSART_vInit(APP_MOBILE_USART, &uart, &uart_clock);
	MUSART_vEnable(APP_MOBILE_USART);
	MUSART_vRxIntStatus(APP_MOBILE_USART, MUSART_DISABLE);
	/**********************************************************************************************/

	/******************************** DMA CONFIGURATIONS FOR USART ********************************/
	dmat.SrcAddr = (u32*)MUSART_u32EnableRxDMA(APP_MOBILE_USART);
	dmat.DstAddr = (u32*)APP_u8String;
	dmat.Length = APP_MOBILE_MESSAGE_LENGTH;
	dmat.Size = MDMA_SIZE_BYTE;
	dma.Channel = MDMA_CHANNEL_4;
	dma.PriorityLevel = MDMA_PRIORITY_HIGH;
	MDMA_vDirectInit(DMA2, MDMA_STREAM_5, &dma);
	MDMA_vStart(DMA2, MDMA_STREAM_5, &dmat);
	/**********************************************************************************************/

	/*********************************** GPT PWM CONFIGURATIONS ***********************************/
	MGPT_PWMInitTypeDef gpt = {MGPT_CHANNEL_1, MGPT_PWM_MODE_1, 10000, 1,
							MGPT_ALLIGNMENT_EDGE_MODE, 0, MGPT_CHANNEL_OUTPUT_ACTIVE_HIGH};
	MGPT_vPWMInit(GPT3, &gpt);

	/**********************************************************************************************/
}

int main(void) {

	APP_vInit();

    /* Loop forever */
	while(1) { }
}
